global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'alerts@your-domain.com'
  smtp_auth_username: 'alerts@your-domain.com'
  smtp_auth_password: 'your-app-password'
  smtp_require_tls: true
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'
  routes:
    - match:
        severity: critical
      receiver: 'critical-alerts'
      group_wait: 10s
      group_interval: 5m
      repeat_interval: 12h
    - match:
        severity: warning
      receiver: 'warning-alerts'
      group_wait: 10s
      group_interval: 10m
      repeat_interval: 4h
    - match:
        alertname: NodeDown
      receiver: 'infrastructure-alerts'
      group_wait: 0s
      group_interval: 1m
      repeat_interval: 30m
    - match:
        alertname: DiskSpaceCritical
      receiver: 'infrastructure-alerts'
      group_wait: 0s
      group_interval: 1m
      repeat_interval: 30m

receivers:
  - name: 'web.hook'
    webhook_configs:
      - url: 'http://uptime-kuma:3001/api/push/webhook'
        send_resolved: true
        http_config:
          bearer_token: 'your-webhook-token'

  - name: 'critical-alerts'
    email_configs:
      - to: 'admin@your-domain.com'
        send_resolved: true
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
        channel: '#alerts'
        title: '🚨 CRITICAL ALERT: {{ .GroupLabels.alertname }}'
        text: |
          *Alert:* {{ .GroupLabels.alertname }}
          *Summary:* {{ .CommonAnnotations.summary }}
          *Description:* {{ .CommonAnnotations.description }}
          *Severity:* {{ .CommonLabels.severity }}
          *Instance:* {{ .CommonLabels.instance }}
          
          Please investigate immediately!
        send_resolved: true
        actions:
          - type: button
            text: 'View Dashboard'
            url: 'https://your-domain.com/grafana'
          - type: button
            text: 'View Logs'
            url: 'https://your-domain.com/grafana/explore'

  - name: 'warning-alerts'
    email_configs:
      - to: 'alerts@your-domain.com'
        send_resolved: true
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
        channel: '#monitoring'
        title: '⚠️ WARNING: {{ .GroupLabels.alertname }}'
        text: |
          *Alert:* {{ .GroupLabels.alertname }}
          *Summary:* {{ .CommonAnnotations.summary }}
          *Description:* {{ .CommonAnnotations.description }}
          *Severity:* {{ .CommonLabels.severity }}
          *Instance:* {{ .CommonLabels.instance }}
        send_resolved: true

  - name: 'infrastructure-alerts'
    email_configs:
      - to: 'admin@your-domain.com'
        send_resolved: true
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
        channel: '#infrastructure'
        title: '🔧 INFRASTRUCTURE: {{ .GroupLabels.alertname }}'
        text: |
          *Alert:* {{ .GroupLabels.alertname }}
          *Summary:* {{ .CommonAnnotations.summary }}
          *Description:* {{ .CommonAnnotations.description }}
          *Severity:* {{ .CommonLabels.severity }}
          *Instance:* {{ .CommonLabels.instance }}
          
          Infrastructure issue detected!
        send_resolved: true
        actions:
          - type: button
            text: 'View System Dashboard'
            url: 'https://your-domain.com/grafana/d/system-overview'
          - type: button
            text: 'SSH to Server'
            url: 'ssh://your-server-ip'

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'cluster', 'service']
  - source_match:
      alertname: 'NodeDown'
    target_match_re:
      alertname: '.*'
    equal: ['instance']

templates:
  - '/etc/alertmanager/templates/*.tmpl'